### ISSUE TITLE
Jenkins Pipeline / Checkout Configuration

### ISSUE THREAD

**Issue by JoA-MoS** [nrwl/nx-jenkins-build#1]
I am really excited about this example repo but one thing I have experienced is setting the base the way you are setting it does not work in our implementation.  Could you include a screenshot of your pipeline configuration similar to this, so others can see?

![jenkins-pipline-config](https://user-images.githubusercontent.com/5566979/73554885-6518c680-4401-11ea-9550-073d2e99c1b9.png)

**Comment by JoA-MoS** [comment]
Also, it might be cool to see the blue ocean representation of these after they run

**Comment by josecolella** [comment]
@JoA-MoS He is using a Jenkinsfile to declare the pipeline.

**Comment by JoA-MoS** [comment]
You still need to configure Jenkins to know how to connect to your repo. Even in a multi-branch or multi project repo there was a step where you configured Jenkins to know where your repo is located.

For instance he uses origin/master but in our environment we have to use remotes/origin/master for our base.
